#!/usr/bin/env bash
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database keystone;grant all privileges on keystone.* to keystone@'node0' identified by 'password';grant all privileges on keystone.* to keystone@'%' identified by 'password';flush privileges;"
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database glance;grant all privileges on glance.* to glance@'node0' identified by 'password';grant all privileges on glance.* to glance@'%' identified by 'password';flush privileges;"
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database nova;grant all privileges on nova.* to nova@'node0' identified by 'password';grant all privileges on nova.* to nova@'%' identified by 'password';flush privileges;"
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database nova_api;grant all privileges on nova_api.* to nova@'node0' identified by 'password';grant all privileges on nova_api.* to nova@'%' identified by 'password';flush privileges;"
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database nova_cell0;grant all privileges on nova_cell0.* to nova@'node0' identified by 'password';grant all privileges on nova_cell0.* to nova@'%' identified by 'password';flush privileges;"
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database nova_placement;grant all privileges on nova_placement.* to nova@'node0' identified by 'password';grant all privileges on nova_placement.* to nova@'%' identified by 'password';flush privileges;"
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database neutron_ml2;grant all privileges on neutron_ml2.* to neutron@'node0' identified by 'password';grant all privileges on neutron_ml2.* to neutron@'%' identified by 'password';flush privileges;"
mysql --user="test" --password="615243" -h 10.10.7.1 --execute="create database cinder;grant all privileges on cinder.* to cinder@'node0' identified by 'password';grant all privileges on cinder.* to cinder@'%' identified by 'password';flush privileges;"

